### ISSUE TITLE
Allow non-parallelism.

### ISSUE THREAD

**Issue by JayKickliter** [nmandery/rasterh3#4]
I'm using this crate to great success, but due to a serial bottleneck, I'd like to rayon to parallelize an outer loop that calls `to_cells`. Just as I've experienced in the past, these non-cooperating nested ParallelIterators are killing perf. The solution could be either a feature gate, or something along the lines of `to_cells` (serial) and `to_cells_par` (parallel).

**Comment by nmandery** [comment]
Great that the crate is helpful to you.

I am prefering the feature gate, as this allows removing the rayon dependency completely. I will try t get to adding this soon.
